#!/usr/bin/env bash

##############################################################################
##
##  Changelog creation script for use with Git Shell & Drone.io
##  Created by Funwayguy for BetterQuesting
##  WARNING: Script must be identical in every branch to function correctly
##  and therefore should be downloaded during build instead
##
##############################################################################

# Update branches
git fetch

# Legacy changelog
echo "CI_MOD_VERSION" > version.txt
echo "http://minecraft.curseforge.com/projects/better-questing" >> version.txt
git log -1 --pretty=format:"%B" >> version.txt
# Padding to prevent legacy logs showing the new entries
echo "" >> version.txt
echo "" >> version.txt
echo "" >> version.txt

# 1.7.10 changelog
echo "git_branch:1.7.10" >> version.txt
git log origin/1.7.10 -1 --pretty=format:"%H%n%B" >> version.txt

# 1.8.9 changelog
echo "git_branch:1.8.9" >> version.txt
git log origin/1.8.9 -1 --pretty=format:"%H%n%B" >> version.txt

# 1.9 changelog
echo "git_branch:1.9" >> version.txt
git log origin/1.9 -1 --pretty=format:"%H%n%B" >> version.txt

# 1.10 changelog
echo "git_branch:1.10" >> version.txt
git log origin/1.10 -1 --pretty=format:"%H%n%B" >> version.txt

# dev7 changelog
echo "git_branch:dev7" >> version.txt
git log origin/1.7.10 -1 --pretty=format:"%H%n%B" >> version.txt

# dev10 changelog
echo "git_branch:dev10" >> version.txt
git log origin/1.10 -1 --pretty=format:"%H%n%B" >> version.txt

# dev10 changelog
echo "git_branch:dev11" >> version.txt
git log origin/dev11 -1 --pretty=format:"%H%n%B" >> version.txt