#!/bin/bash

FILE_NAME=`echo "BetterQuesting-BQ_VER_KEY.jar"`
FILE_LOCATION=`echo "./build/libs/$FILE_NAME"`
CHANGE_LOG=`git log -1 --pretty=format:"%B"`

#See https://github.com/curseforge/api for how to retrieve game version numbers
JSON=`printf '{"changelog": "%s", "gameVersions": [4449], "releaseType": "release"}' "$CHANGE_LOG"`

echo "Uploading $FILE_NAME to Curse Forge..."
echo
RESPONSE=`curl -H "X-Api-Token: $CURSE_API_KEY" -X POST  -F metadata="$JSON"  -F file="@$FILE_LOCATION" https://minecraft.curseforge.com/api/projects/238856/upload-file`
echo
FID=${RESPONSE:6}
FID=${FID:0:${#FID}-1}
echo $FID

FILE_NAME=`echo "BetterQuesting-deobf-BQ_VER_KEY.jar"`
FILE_LOCATION=`echo "./build/libs/$FILE_NAME"`


JSON=`printf '{"changelog": "%s", "parentFileID": %s, "releaseType": "release"}' "$CHANGE_LOG" "$FID"`
echo "Uploading $FILE_NAME to Curse Forge..."
echo
RESPONSE=`curl -H "X-Api-Token: $CURSE_API_KEY" -X POST  -F metadata="$JSON"  -F file="@$FILE_LOCATION" https://minecraft.curseforge.com/api/projects/238856/upload-file`